return {}
-- return {
--   'joaomsa/telescope-orgmode.nvim',
--   after = {
--     'telescope.nvim',
--     'orgmode',
--   },
--   config = function()
--     require('telescope').load_extension 'orgmode'
--   end,
--   keys = {
--     {
--       '<leader>so',
--       function()
--         require('telescope').extensions.orgmode.search_headings()
--       end,
--     },
--   },
-- }
-- return {
--   'joaomsa/telescope-orgmode.nvim',
--   dependencies = {
--     { 'nvim-orgmode/orgmode' },
--     { 'nvim-telescope/telescope.nvim' },
--   },
-- }
